### ISSUE TITLE
Slow performance due to many AIS targets

### ISSUE THREAD

**Issue by martijn-heil** [SignalK/freeboard-sk#101]
Sailing on congested waters (Port of Rotterdam, Port of Amsterdam and nearby rivers and canals for my own experience), freeboard becomes almost unusably slow on mobile devices. On a full-fledged desktop computer it becomes a little slower but no real problems. However, on smartphones running Firefox Mobile it becomes very slow.
Even on a relatively powerful smartphone like a Galaxy Note 10+ it becomes almost unusable.
When I enable 'Hide Vessels' and reload the page, the performance is back to normal and freeboard is very responsive.
I've tried limiting the AIS target range to 5 nautical miles, but even with such small range the performance is bad, albeit a little better, up to properly usable, depending on where I'm at. 
At full range I must be receiving hundreds if not thousands of vessels, I don't know for sure because I have no easy way of counting the AIS targets, but on the map I'm receiving more or less half of the Netherlands, vessels far inland and on coastal waters.
Maybe when I am home I can do some more detailed performance analysis, but this is not possible right now.
I understand that this is probably a rather complex issue, but it would be nice if perhaps the performance related to AIS targets could be optimized a bit more.

**Comment by panaaj** [comment]
Freeboard-sk has options to adress this.... there is a setting to limit target processing to only those within a certain `radius` to reduce the number of targets that are processed and displayed.

Additionally, I have seen my RPi struggle with a large number of targets when certain plugins are enabled without any clients connected. It is definitely a device resource issue.

FYI can run a similar configuration that causes my RPi to struggle with no issues at all using:
- Signal K server running in docker instance on my laptop
- Using laptop browser to load Freeboard-sk from docker hosted server. 

Freeboard-sk tries to be as efficient as possible with map rendering due to the potentially large number of elements to display but map rendering requires resource.

**Comment by tkurki** [comment]
@panaaj Martijn's stated that the problem is on a separate device so I don't think this is about server performance, and he already tried the `radius` trick...

Interested in this, as I made some poor choices with `vesselpositions` and its perf with a large number of AIS targets is abysmal. One strategy that I have been thinking of is monitoring how busy the event loop is and updating the display in batches and not target by target, with batch interval based on "busyness" of the browser.

**Comment by panaaj** [comment]
@tkurki FYI as it stands currently communication with the signal K stream is done via a web worker (so as to not impact rendering). The worker posts a message to main thread at 1 second intervals where it is then rendered.
Only updated targets are rendered on every cycle using openlayers (v5 in FB v1.16.x & v6 in FB 1.17.0)

**Comment by panaaj** [comment]
closed due to inactivity
