### ISSUE TITLE
Anchor watch: server may not support?

### ISSUE THREAD

**Issue by bkcorwin** [SignalK/freeboard-sk#109]
Hello, I am trying to get the anchor watch function in freeboard to work.  I am getting the error "server returned an error. This function may not be supported by your server" 

I have installed the plugins that I think are whats required based on the documentation.  They are (Freeboard-sk-helper, signalk-anchoralarm-plugin).

Yet I still get this error?  Can anyone assist?

thanks much

**Comment by panaaj** [comment]
The only plugin required for this functionality is `signalk-anchoralarm-plugin`.
Once it is installed, ensure it is enabled by checking in the Plugin Config screen.
![image](https://user-images.githubusercontent.com/38519157/163906300-9b2393b1-fba9-4816-a9f0-91c1a47ff43c.png)

It is the plugin that provides the api endpoints required for Freeboard to operate so the message you are seeing is because Freeboard received an error back from the server when making a request to set the anchor position / radius.

The following screenshot shows the error received back from the server when the plugin is disabled.
If you are still receiving errors you can check your browsers console to see what error is received when the request to set the anchor alarm is made.

You can also use your browser to test the api endpoint provided by the plugin... `http://your_server_address:3000/signalk/v1/api/vessels/self/navigation/anchor`.

![image](https://user-images.githubusercontent.com/38519157/163907193-cba82e1c-5dac-4c2e-8b3a-352f3769b0b7.png)

**Comment by bkcorwin** [comment]
![Capture](https://user-images.githubusercontent.com/16884141/164061445-5f46718b-4252-4dcc-978b-6b4f53e41a2a.PNG)

This all makes sense and i've checked a lot of this already.   But what confuses me is my plugin page is different than yours.  I dont see an option to enable, just configure?
