### ISSUE TITLE
Longer timer for 'Other vessels' settings

### ISSUE THREAD

**Issue by Donixon** [SignalK/freeboard-sk#126]
Great product, like I have said many times! But I would like to change the 'Other vessels' settings, specifically the 'Remove AIS target after', to something bigger then 9 minutes.
We don't use your the product on a boat, like where it's meant to be for, but as a dashboard to see our own fleet in the port of Rotterdam. So it's desirable to change this to at least 24hours? A boat will most likely be turned on at least once a day I guess. Not sure if performance wise this is possible? Otherwise maybe a 'don't remove AIS targets' setting? But also, that would be so specific to me and not needed for others.

Think this will be a nice feature, so we will see our own boats in our own port for longer then 9 minutes. 

Thanks in advance!

**Comment by panaaj** [comment]
Will add more options as per screenshot. If more choices between 1hr and 24hrs are required they are easily added.
Performance impacts will depend on how many targets are displayed, but in past testing running Freeboard-SK on a laptop browser (rather than RPi browser) with thousands of targets displayed there was no significant impact.

![image](https://github.com/SignalK/freeboard-sk/assets/38519157/74b0181f-6189-4344-93dc-eed3ecd5ef1c)

Will be available in the next release.

**Comment by Donixon** [comment]
> Will add more options as per screenshot. If more choices between 1hr and 24hrs are required they are easily added. Performance impacts will depend on how many targets are displayed, but in past testing running Freeboard-SK on a laptop browser (rather than RPi browser) with thousands of targets displayed there was no significant impact.
> 
> ![image](https://user-images.githubusercontent.com/38519157/277085965-74b0181f-6189-4344-93dc-eed3ecd5ef1c.png)
> 
> Will be available in the next release.

Damn, great! Running it in a Docker on a server. So I don't think ill notice performance issues then. 

Thanks alot!
