### ISSUE TITLE
FeatureRequest: Vessel position lock position for 'north up'

### ISSUE THREAD

**Issue by joabakk** [SignalK/freeboard-sk#29]
For 'vessel up', the vessel is positioned below centre, so you can see more of what is coming ahead. This does not make as much sense with 'north up'. Perhaps it could be centered or similarly positioned off center to the north if on a southerly route? Positioning so much to the opposite of the course may be a bit disturbing if on an unstable course

**Comment by rob42** [comment]
Its a hang-over from the earlier version without screen rotation! 

The vessel position is [center(x), 0.33*(y)] from bottom left when the "Follow vessel" is on. When Follow vessel is off its not set, you need to scroll the screen manually.

A better algorithm would be good, but beware it may make the vessel jump about stupidly as you turn. Even the current algo had to have quite a bit of tweaking to settle things down reasonably :-)

The openlayers.org site has some fly-by examples that may be useful. They slide the chart/location from x to y instead of jumping.

**Comment by joabakk** [comment]
I have found the iSailor way to do this quite nice. You "lock"the vessel position while panning, and it follows from there. I think that if you lock the vesel outside the chart, it will just indicate with an arrow where it is, and if it comes into the chart, it starts following
