### ISSUE TITLE
Using NOAA Quilted .mbtiles?

### ISSUE THREAD

**Issue by zubenubi** [SignalK/freeboard-sk#33]
Hi,
I noted in another issue that we need to edit lib/addlayers in order to use other map formats. Does that extend to the .mbtiles that are now being quilted and distributed by NOAA? I see that these automatically appear in the Charts List, but I am not able to see anything when clicking Show/Hide buttons.

**Comment by rob42** [comment]
The charts list is auto-populated by simply scanning the mapcache dir for sub-dirs. Hence it finds the mbtiles dirs but doesnt understand them. So yes it will need some adjustment

**Comment by zubenubi** [comment]
Thanks for speedy answer!
So I am looking for  the addlayers.js file in my signalk-server-node install on a rpi3 but no joy.  These .mbtiles files I understand to be SQLite dbs, correct? What kind of adjustment would I need to make?

**Comment by rob42** [comment]
Not sure - I havent tried using them. If you have js skills the google for openlayers3 and mbtiles - ol3 is the underlying map layer lib.

The code here will need adjustment to read the mbtiles data: https://github.com/SignalK/freeboard-sk/blob/6217ff5d7e05dec5a5d1bd9cd762c8f6e315769c/lib/charts.js#L230-L270

**Comment by tkurki** [comment]
To a client application (a browser app like Freeboard) mbtiles charts are normal tiled charts: theSK Node server already takes care of digging out the chart metadata from the mbtiles file and serves the individual map tiles.

The response to `/signalk/v1/api/resources/charts` will look something like this
```
{
  "mbtiles-file-name.mbtiles": {
    "identifier": "mbtiles-file-name",
    "name": "Name from the mbtiles file",
    "description": "Description from the mbtiles file",
    "bounds": [
      19.105224609375,
      65.84776766596988,
      27.88330078125,
      59.645540251443215
    ],
    "minzoom": 4,
    "maxzoom": 15,
    "format": "png",
    "tilemapUrl": "/charts/mbtiles-file-name.mbtiles/{z}/{x}/{y}",
    "type": "tilelayer",
    "scale": "250000"
  }
}
```
So you should be to change Freeboard code so that if server response already includes the necessary information no need to do the secondary http request, just construct the OpenLayers layer.

Btw have you tried tuktuk-chart-plotter, installable from SK Node Server's app store? It supports mbtiles out of the box (to be precise, the server's mbtiles code is mostly copypaste from tuk-tuk's internal server).

**Comment by zubenubi** [comment]
Thanks for the quick responses. I installed tuktuk from the appstore but ran into a permissions issue (signalk-server-node is running as 'pi' - not root). So I sshd to the machine and ran (as root) 'npm install tuktuk-chart-plotter'. Seems like success on install but configuration and start/stop is going to take me a bit. I do like the look of freeboard and so will investigate the js changes that need to be made, although Im no js guru

**Comment by tkurki** [comment]
This is a sidetrack, but there should be no need for installing things as root. I assume you did at least part of your original installation as root and the trouble stems from that.

The easiest way to restart the SK server is to reboot the machine. Tuktuk needs no further configuration.

**Comment by panaaj** [comment]
#51 adds support for mbtiles served from`resources/charts`
