### ISSUE TITLE
bug?: looking for tilemapresources in wrong place

### ISSUE THREAD

**Issue by joabakk** [SignalK/freeboard-sk#41]
The error I get from the one map I have stored states that it is looking for `[server]/signalk/v1/api/resources/charts/L6-8-24-24-8_1/%7Bz%7D/%7Bx%7D/%7By%7D/tilemapresource.xml`

Shouldn't it look in `[server]/signalk/v1/api/resources/charts/L6-8-24-24-8_1/tilemapresource.xml` instead ? That is where freeboard-installer placed the xml file

**Comment by rob42** [comment]
/%7Bz%7D/%7Bx%7D/%7By%7D/ is urlencoded version of {z}/{x}/{y}, which should have values z,x,y inserted in those positions. That should only be for the tiles themselves, the tilemapresource.xml should be in the root of the maps tile pyramid.

Is it only the one chart? If so look for something unique in the setup, also in the filenames, especially if it came from windows. Windows uses cp1256 charset instead of utf-8, and will insert strange chars as a result.
