### ISSUE TITLE
[enhancement] Add the keys of keyboard for control

### ISSUE THREAD

**Issue by free-x** [SignalK/freeboard-sk#67]
Hi,

is it possible to add the control on map with keys from keyboard? 
+, - , Right, Left, Up, Down, PageUp, PageDown

Regards
free-x

**Comment by panaaj** [comment]
In the current version the keyboard cannot be used to zoom / scroll the map, this is due to the user experience being made a little inconsistent by the fact that keystrokes are only sent to the map it has focus. 
So you get the experience where: 
- after the application loads the keys to scroll/pan don't  work (map does not have focus)
- click on the map and the keys to scroll/pan will work 
- open a menu, etc and the keys to scroll/pan don't work (map loses focus)
- you need to click back on the map for them to work again.

I'd expect that a user who prefers to use the keyboard would be frustrated if they did not work consistently after all menu and dialog interactions.

**Comment by tkurki** [comment]
But isn't all this fixable?
- focus on map on load and when menus etc are closed 
- close menus etc with Escape key

**Comment by panaaj** [comment]
Added to v1.60 release
