### ISSUE TITLE
Chartname in footer

### ISSUE THREAD

**Issue by AndreasSchutz** [SignalK/freeboard-sk#88]
Hi
I think that a very useful feature would be to add the chart name in the "footer" on freeboard-sk (where the Lat/Long and zoom level is). That would make it easy to know what chart you are reading when you have layered charts.

I have arranged my charts in three layers; 1) "global coastline zm 1-9, 2) overview charts from zm 9-12 and 3) navigation charts from zm 12 to 17.
When I zoom back and forth, it is hard to see what chart I'm actually looking at. A footer that reads:
N55.12345° E15.12345° Zm:15 Chart: Oslo fjorden 2019-03-12
would help a lot. Displaying "name" or "description" from "chart properties" would be perfect.

**Comment by panaaj** [comment]
I'm not sure how "reliable" this might be to implement.
There is no means to reliably get the chart tiles currently visible from OpenLayers, so the solution could only guess by looking at the chart layer stack and the zoom level.... but that is no guarantee that what is displayed will match due to caching, etc.

I'm guessing there'd be more complaints about the wrong chart name being displayed than  ot showing one at all.

**Comment by AndreasSchutz** [comment]
Yes, I see. Maybe a way would be to "watermark" the layer with something (The chart name?). But then you would have issues when displaying many charts on the same zoom level. Does the mouse know which chart it scrolls over? I guess not.

A last resort could be to integrate the charts list with the chart layer view so that you could drag the charts in the charts list already.... You would get rid of one hierarchy and you could use the "fold-out" menu (less cluttering) as a guide or legend.

**Comment by panaaj** [comment]
Chart re-ordering has been moved to operate within the chart list.

![image](https://user-images.githubusercontent.com/38519157/102686726-6af5e100-4239-11eb-8eb0-ef3621cccd06.png)
