### ISSUE TITLE
Support NOAA charts out of the box

### ISSUE THREAD

**Issue by mgrouch** [SignalK/freeboard-sk#92]
Support NOAA charts out of the box is needed 
Just like AvNav has it with avnav-mapproxy-plugin.
You can see how their implementation works by downloading this 
OS image for raspberry pi 4

https://github.com/bareboat-necessities/lysmarine_gen

Thanks,
--MG

**Comment by panaaj** [comment]
@mgrouch So if I understand correctly, AvNav can source WMS maps via the `MapProxy` product.

Currently the `signalk-charts-plugin` performs a very basic version of what the MapProxy product does... effectively hosts MBTiles and acts as a provider for the `./resources/charts` path. 
_Recent changes to charts plugin allows maps to be identified as WMS and specify the layers required._

The benefit of the MapProxy is it provides the ability to cache maps (in a very controlled way) so it would need to be installed and configured on the Signal K server.

Freeboard can display WMS maps, currently though it honors the Signal K standard and uses entries in the `charts` path.

Possible soluitions include:
1. Configure the charts-plugin with WMS map entries where the URL points to the MapProxy.

1. Create a MapProxy plugin that acts as a provider for the `./resources/charts` path.

1. Divert from SIgnal K spec and provide a means for Freeboard to specify an alternate / additional map source(s) and point those to charts served by the proxy.

Option 3 goes against Freeboard's tenet of being Signal K spec compliant so for me would be a last resort...(others may disagree but happy to have my mind changed!)

Option 2 is more aligned with the Signal K "vibe" and option 1 requires no change at all.

This all being said if the issue is adding additional chart formats WMTS, KML, etc then that is a different issue and can be addressed (as WMS support was).

ping @tkurki

**Comment by tkurki** [comment]
You can already use NOAA charts, just download them in mbtiles format from https://tileservice.charts.noaa.gov/tileset.html#50000_1-locator. No Mapproxy needed.

Other than that I am with Adrian with 1 and 2. 

Mapproxy is conceptually similar to Influxdb: a separate service, I don't see SK server supporting it out of the box. but we can add integration with it in a plugin, either in the charts plugin or as a separate plugin. So that you can configure where your (separately installed) mapproxy is and possibly get chart metadata (extent, zoomlevels etc) automatically. I'd prefer this being in the charts plugin.

Pull Requests are welcome, but I don't see this being a Freeboard issue.
