### ISSUE TITLE
Feature request: Ability to filter AIS targets based on `navigation.state`

### ISSUE THREAD

**Issue by martijn-heil** [SignalK/freeboard-sk#99]
It would be a nice feature to be able to filter AIS targets based on their navigational state (`navigation.state`), so you could for example filter out all moored vessels. In busy ports (own experience being the Port of Amsterdam), the sheer amount of moored vessels with their AIS on clutters the map to such an extent that it becomes difficult to distinguish actual moving ships from harmless moored ships.

In the specific case of filtering out moored (and perhaps some other states like anchored) vessels, there is a bit of a safety issue in that I believe you can sail around with AIS while broadcasting your state as being 'moored'. There may need to be a safety check in the implementation of such a feature that confirms that moored ships are indeed not moving, so that if they are in fact moving, they should be shown regardless of such a filtering setting.

**Comment by panaaj** [comment]
The ability to filter AIS targets based on state has merit and I will look to implement this feature.
Initially I am thinking that this would apply to `vessels` only and not other types such as `aircraft`, `SaR` and `AtoN`.

As for the validity of the vessel state, this is a data quality issue and I don't think it's the job of the client app to fix this as:
1. It assumes the user of the app knows what rules are being applied to "correct the state"
2. The rules could change as part of a app update without the user knowing
3. Disparity in results when compared to other apps that may be in use... i.e. vessels filtered on a particular state appearing in one app and not the other.

For this reason I feel that any state correction should be applied at a server level so that all apps operate with the same data set.
This would be a good use case for a `Signal K server plugin`.

**Comment by martijn-heil** [comment]
> The ability to filter AIS targets based on state has merit and I will look to implement this feature.
> Initially I am thinking that this would apply to `vessels` only and not other types such as `aircraft`, `SaR` and `AtoN`.
> 
> As for the validity of the vessel state, this is a data quality issue and I don't think it's the job of the client app to fix this as:
> 
>     1. It assumes the user of the app knows what rules are being applied to "correct the state"
> 
>     2. The rules could change as part of a app update without the user knowing
> 
>     3. Disparity in results when compared to other apps that may be in use... i.e. vessels filtered on a particular state appearing in one app and not the other.
> 
> 
> For this reason I feel that any state correction should be applied at a server level so that all apps operate with the same data set.
> This would be a good use case for a `Signal K server plugin`.

Yes I agree, a server plugin to correct the state seems like a better solution to this problem.

**Comment by martijn-heil** [comment]
As a side note, on the very first day using this filter for moored vessels I've already encountered two Rhine barges which had their AIS on 'moored' even though they were motoring along, causing them not to appear on the map.
Called one of them on the VHF stating that his AIS was on moored, the skipper replied that he'd look into it and within a minute or so his AIS state was back to it's proper value instead of 'moored'.

This confirms my suspicion that this filter has a significant element of danger to it and really does need to be combined with a new vessel state-correcting plugin.

**Comment by tkurki** [comment]
Just an additional note here that we should keep the AIS-originated value accessible and not overwrite it in a plugin - so imho it should not be a "correcting" plugin. We do have the mechanism for having multiple values for a path, the clients could give precedence to the value from the plugin. `derived-navigation-state` or something.
